### PR TITLE
HEP-1: Value Annotations

### PR DESCRIPTION
**Pull request by aperezdc**
This adds the text for the initial version version of HEP-1

### CODE REVIEW

**Comment by aperezdc** [comment]
@ajdiaz @ogarcia: PTAL.

**Comment by ajdiaz** [comment]
:+1: Looks good to me

**Comment by aperezdc** [comment]
Merged manually onto `gh-pages`. GitHub does not allow to change the branch onto which a PR is to be merged :disappointed:

**Comment by ogarcia** [comment]
:+1:

**Pull request closed without merging**
